package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallReview;
import org.linlinjava.litemall.db.domain.LitemallReviewExample;

public interface LitemallReviewMapper {
    long countByExample(LitemallReviewExample example);

    int deleteByExample(LitemallReviewExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(LitemallReview record);

    int insertSelective(LitemallReview record);

    List<LitemallReview> selectByExampleWithBLOBs(LitemallReviewExample example);

    List<LitemallReview> selectByExample(LitemallReviewExample example);

    LitemallReview selectByPrimaryKey(Integer id);

    int updateByExampleSelective(@Param("record") LitemallReview record, @Param("example") LitemallReviewExample example);

    int updateByExampleWithBLOBs(@Param("record") LitemallReview record, @Param("example") LitemallReviewExample example);

    int updateByExample(@Param("record") LitemallReview record, @Param("example") LitemallReviewExample example);

    int updateByPrimaryKeySelective(LitemallReview record);

    int updateByPrimaryKeyWithBLOBs(LitemallReview record);

    int updateByPrimaryKey(LitemallReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_review
     *
     * @mbg.generated
     */
    LitemallReview selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_review
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") LitemallReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_review
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}